# Generated by Django 4.2 on 2023-04-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_review_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
